name: Contexts
run-name: Contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITTEN_VAR: "workflow"

jobs:
  ehco-data:
    runs-on: ubuntu-latest

    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"

    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Repository: ${{ github.repository }}"

      - name: Retrieve Variable
        run: echo ${{ vars.MY_VAR }}

      - name: Pring Env variables
        run: |
          echo "Workflow env ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten var ${{ env.MY_OVERWRITTEN_VAR }}"

  echo-data2:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
          echo "Workflow env $env.MY_WORKFLOW_VAR"
          echo "Overwritten var $env.MY_OVERWRITTEN_VAR"
