name: Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: inputs.debug == true
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: "[debug] Pring when triggerd from current branch ex: 'expressions'"
        if: inputs.debug == true && github.ref_name == 'expressions'
        run: |
          echo "I was triggered from the branch: ${{ github.ref_name }}"

      - name: "Greeting"
        run: |
          echo "Hello, world"
