name: Event Filters and Activity Types

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - filter-activity-types

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Running whenever a PR is opened or synchronized and base branch is filter-activity-types"
