name: Using actions

on: 
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/chckout@v4
            - name: Pringitng Folders
              run: ls

        # 0. Checkout code
        # 1. Install deps of  react app
        # 2. Execute autmated tests

